services:
  web:
    build: .
    ports:
      - "8080:8501"
    volumes:
      - type: bind
        source: ./src
        target: /app
  db:
    image: "postgres:16.4"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
